#TODO: IMPLEMENT
@url = http://localhost:8080/api/team

GET {{url}}/1 HTTP/1.1

###

GET {{url}}/all/1 HTTP/1.1

###

POST {{url}}
Content-Type: application/json

{
  "teamName": "The Trivia Titans",
  "game": {
    "gameId": 1
  }
}